version: 1.0.0.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: >-
    dotnet restore
build:
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
    name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: nVErxJrUI4AStPan9b32g0YBTGMkjtMrehnItai8OYFy8EQNhDFWZNk5VReqC/pB
  artifact: /Akismet.Umbraco\.(.*)\.nupkg/
