version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: >-
    nuget restore src\Akismet.Umbraco.sln

    nuget pack NuGet\Akismet.Umbraco9.nuspec
build:
  verbosity: minimal
artifacts:
- path: src\Akismet.Umbraco\bin\Release\Akismet.Umbraco9.Core.*.nupkg
  name: NuGet
- path: Akismet.Umbraco9.*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: WkVJb3oiApwevIMc38fgngZXhkOS3qktXf4sSwZ3YRHVtEE/cugn368uZUose63E
  artifact: /Akismet.Umbraco9\.(.*)\.nupkg/