version: 1.2.2.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- ps: >-
    $version = '1.2.2'

    (Get-Content -path src\Akismet.Umbraco8\Akismet.Umbraco8.csproj -Raw) -replace '<Version>(.*)</Version>',"<Version>$version</Version>"| Set-Content -Path src\Akismet.Umbraco8\Akismet.Umbraco8.csproj

    nuget pack NuGet\Akismet.Umbraco8.nuspec -Version $version -p "commitid=$env:APPVEYOR_REPO_COMMIT;coreVersion=$version;releaseNotes=$env:APPVEYOR_REPO_COMMIT_MESSAGE$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"

    (Get-Content -path src\Akismet.Umbraco8\Akismet.Umbraco8.csproj -Raw) -replace '%releaseNotes%',"$env:APPVEYOR_REPO_COMMIT_MESSAGE$env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED"| Set-Content -Path src\Akismet.Umbraco8\Akismet.Umbraco8.csproj

    nuget restore src\Akismet.Umbraco8.sln
build:
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
  name: NuGet
for:

-
 branches:
   only:
     - main

 deploy:
 - provider: NuGet
   api_key:
     secure: PZ96+4psSOrS2xFAX+Ir1F1+4MQhGlO9Pq2J8oAA2LDFh+6QCqKPxnOztka9I8pv
   artifact: /Akismet.Umbraco8\.(.*)\.nupkg/
