version: 3.0.0.{build}
image: Visual Studio 2022
configuration: Release
before_build:
- cmd: >-
    dotnet restore
build:
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
    name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: PZ96+4psSOrS2xFAX+Ir1F1+4MQhGlO9Pq2J8oAA2LDFh+6QCqKPxnOztka9I8pv
  artifact: /Akismet.Umbraco\.(.*)\.nupkg/
