version: 1.0.0.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: >-
    dotnet restore
build:
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
    name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: 1ccOBZHCoPjWklcbi1Lf6ED+4muXi3r21eswoSuzbi7C1QDhcQC+MkXA5fBd4XNL
  artifact: /Akismet.Umbraco\.(.*)\.nupkg/
