version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: >-
    nuget restore Akismet.UmbracoForms8.Workflow\Akismet.UmbracoForms8.Workflow.sln
build:
  verbosity: minimal
artifacts:
- path: Akismet.UmbracoForms8.Workflow\Akismet.UmbracoForms8.Workflow\bin\Release\Akismet.UmbracoForms8.Workflow.*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: nVErxJrUI4AStPan9b32g0YBTGMkjtMrehnItai8OYFy8EQNhDFWZNk5VReqC/pB
  artifact: /Akismet.UmbracoForms8.Workflow\.(.*)\.nupkg/
