version: 3.0.0.{build}
image: Visual Studio 2022
configuration: Release
before_build:
- cmd: >-
    dotnet restore
build:
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
    name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: LsY29DHn1PDAZnEuO//RKqEgEJFgd6Rpfel8obzS/8wuMOfzlZgJg5+baot5uyoE
  artifact: /Akismet.Umbraco\.(.*)\.nupkg/
