// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class AkismetUmbracoService {
    public static verifyKey<ThrowOnError extends boolean = false>(options?: Options<any, ThrowOnError>) {
        return (options?.client ?? client).get<boolean, any, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/akismetumbraco/api/v1/verify-key',
            ...options
        });
    }

    public static getStats<ThrowOnError extends boolean = false>(options?: Options<any, ThrowOnError>) {
        return (options?.client ?? client).get<any, any, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/akismetumbraco/api/v1/stats',
            ...options
        });
    }

    public static getComments<ThrowOnError extends boolean = false>(options?: Options<any, ThrowOnError>) {
        return (options?.client ?? client).get<any[], any, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/akismetumbraco/api/v1/comments',
            ...options
        });
    }

    public static getSpamComments<ThrowOnError extends boolean = false>(options?: Options<any, ThrowOnError>) {
        return (options?.client ?? client).get<any[], any, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/akismetumbraco/api/v1/spam',
            ...options
        });
    }

    public static getComment<ThrowOnError extends boolean = false>(options: Options<any, ThrowOnError> & { path: { id: number } }) {
        return (options?.client ?? client).get<any, any, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: `/umbraco/akismetumbraco/api/v1/comment/${options.path.id}`,
            ...options
        });
    }

    public static getSpamCount<ThrowOnError extends boolean = false>(options?: Options<any, ThrowOnError>) {
        return (options?.client ?? client).get<number, any, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/akismetumbraco/api/v1/spam-count',
            ...options
        });
    }

    public static getHamCount<ThrowOnError extends boolean = false>(options?: Options<any, ThrowOnError>) {
        return (options?.client ?? client).get<number, any, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/akismetumbraco/api/v1/ham-count',
            ...options
        });
    }

    public static deleteComment<ThrowOnError extends boolean = false>(options: Options<any, ThrowOnError> & { path: { id: string } }) {
        return (options?.client ?? client).delete<void, any, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: `/umbraco/akismetumbraco/api/v1/comment/${options.path.id}`,
            ...options
        });
    }

    public static reportHam<ThrowOnError extends boolean = false>(options: Options<any, ThrowOnError> & { path: { id: string } }) {
        return (options?.client ?? client).post<void, any, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: `/umbraco/akismetumbraco/api/v1/report-ham/${options.path.id}`,
            ...options
        });
    }

    public static reportSpam<ThrowOnError extends boolean = false>(options: Options<any, ThrowOnError> & { path: { id: string } }) {
        return (options?.client ?? client).post<void, any, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: `/umbraco/akismetumbraco/api/v1/report-spam/${options.path.id}`,
            ...options
        });
    }

    public static checkComment<ThrowOnError extends boolean = false>(options: Options<any, ThrowOnError> & { body: any }) {
        return (options?.client ?? client).post<any, any, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/umbraco/akismetumbraco/api/v1/check',
            ...options
        });
    }
}
