// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl?: string;
};

export type AkismetSubmission = {
    id: number;
    commentDate: string;
    commentType: string;
    commentText: string;
    commentData: string;
    result: string;
    spamStatus: number;
    userIp?: string | null;
    userName?: string | null;
};

export type SpamStats = {
    spam: number;
    ham: number;
    missedSpam: number;
    falsePositives: number;
    accuracy: number;
    timeSaved: number;
};

export type AkismetCommentType =
    | 'comment'
    | 'forum-post'
    | 'reply'
    | 'blog-post'
    | 'contact-form'
    | 'signup'
    | 'message'
    | (string & {});

export type AkismetComment = {
    blogUrl?: string | null;
    userIp?: string | null;
    userAgent?: string | null;
    referrer?: string | null;
    permalink?: string | null;
    commentType?: AkismetCommentType | null;
    commentAuthor?: string | null;
    commentAuthorEmail?: string | null;
    commentAuthorUrl?: string | null;
    commentContent?: string | null;
    commentDate?: string | null;
    commentPostModified?: string | null;
    blogLang?: string | null;
    blogCharset?: string | null;
    isTest?: boolean | null;
};

export type SpamStatus = 'Ham' | 'Spam' | 'Discard';

export type AkismetResponse = {
    spamStatus: SpamStatus;
};
